---
title: "Résumé"
---

You can view or download a PDF version of my résumé here:

📄 [Download My Résumé (PDF)](resume/George_Barahona_Resume_2025_.pdf){download=TRUE}


# Professional Summary

Results-oriented marketing and analytics professional with a strong foundation in data analysis, digital strategy, and performance reporting. Skilled in leveraging analytics tools and programming languages to uncover insights and support decision-making across cross-functional teams.

# Technical Skills

-   **Programming Languages:** R, Python, SQL, etc.\
-   **Web Technologies:** HTML, CSS/SCSS, JavaScript, Quarto, CMS Platforms, Analytics Tools

# Education

| Degree | Year | College / Department | Institution |
|-------------------|------------------|--------------------|-----------------|
| M.S Digital Marketing | Expected 2025 | College of Business | Cal Poly Pomona |
| BA in Business Administration | Completed | College of Business | California State University, Fullerton |

# Work Experience

### Individual Member Coordinator, Specialty Equipment Market Association (SEMA)

*Aug 2024 – Present*

-    Supported the development and launch of SEMA+, a B2C membership program.

-   Led reporting and CRM system integration across IT, marketing, and accounting.

-   Contributed to social strategy, influencer outreach, and campaign development.

-    Engaged with partner brands to expand member benefits and offerings.

-    Responded to inbound inquiries via Outlook.

### Marketing & Leasing Coordinator, The Current / Asset Living

*Oct 2023 – Aug 2024*

-    Managed leasing operations and filled property to 100% occupancy ahead of schedule.

-    Used social analytics tools to manage Instagram content and engagement.

-    Planned and executed on-campus marketing initiatives and outreach efforts.

### Learning & Development Technical Associate, Panda Restaurant Group

*May 2022 – Jun 2023*

-    Launched an internal Rosetta Stone campaign that resulted in full license usage and a waitlist.

-    Maintained LMS operations to ensure compliance and learning support.

-    Provided weekend and early-hour technical support through ServiceNow.

-    Promoted online community values via training discussion facilitation.

### Shift Leader, Chick-fil-A

*Jan 2021 – Jan 2022*

-    Designed training programs on cash handling and operational best practices.

-    Supervised vault closures and final walk-throughs during nightly store shutdowns.

-   Created educational content for staff across multiple operational shifts.
e